// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

/**
 * HoneyChain Smart Contract
 * Stores honey batch data on blockchain.
 * Actual detailed data lives on IPFS (via Pinata).
 * We store only the IPFS CID (hash) + trust score here.
 */
contract HoneyChain {

    // ─── Data Structures ───────────────────────────────────────────────────

    enum BatchStatus { Created, Processing, Approved, FlaggedAdulteration, InTransit, Delivered }

    struct HoneyBatch {
        string batchId;          // Unique ID like "BATCH-001"
        address beekeeper;       // Wallet address of beekeeper
        uint256 trustScore;      // 0-100 score generated by ML
        string ipfsCID;          // Pinata IPFS CID of detailed JSON data
        BatchStatus status;
        uint256 createdAt;       // Unix timestamp
        bool exists;
    }

    struct TransferLog {
        address from;
        address to;
        string role;             // "Beekeeper→Processor", "Processor→Distributor" etc.
        uint256 timestamp;
        string locationCID;      // IPFS CID of location/transport data
    }

    // ─── State Variables ────────────────────────────────────────────────────

    address public owner;        // Admin wallet

    // batchId → HoneyBatch
    mapping(string => HoneyBatch) public batches;

    // batchId → array of transfer logs (chain of custody)
    mapping(string => TransferLog[]) public custodyChain;

    // batchId → flagged or not
    mapping(string => bool) public flagged;

    // All batch IDs for enumeration
    string[] public allBatchIds;

    // ─── Events (frontend/backend can listen to these) ──────────────────────

    event BatchCreated(string batchId, address beekeeper, uint256 trustScore, string ipfsCID);
    event BatchStatusUpdated(string batchId, BatchStatus newStatus);
    event CustodyTransferred(string batchId, address from, address to, string role);
    event BatchFlagged(string batchId, string reason);

    // ─── Modifiers ──────────────────────────────────────────────────────────

    modifier onlyOwner() {
        require(msg.sender == owner, "Only admin can do this");
        _;
    }

    modifier batchMustExist(string memory batchId) {
        require(batches[batchId].exists, "Batch does not exist");
        _;
    }

    // ─── Constructor ────────────────────────────────────────────────────────

    constructor() {
        owner = msg.sender;
    }

    // ─── Core Functions ─────────────────────────────────────────────────────

    /**
     * @dev Called by backend when a new honey batch is created.
     * @param batchId    Unique identifier for this batch
     * @param trustScore ML-generated trust score (0-100)
     * @param ipfsCID    IPFS CID where full batch JSON is stored on Pinata
     */
    function createBatch(
        string memory batchId,
        uint256 trustScore,
        string memory ipfsCID
    ) public {
        require(!batches[batchId].exists, "Batch already exists");
        require(trustScore <= 100, "Trust score must be 0-100");

        batches[batchId] = HoneyBatch({
            batchId: batchId,
            beekeeper: msg.sender,
            trustScore: trustScore,
            ipfsCID: ipfsCID,
            status: BatchStatus.Created,
            createdAt: block.timestamp,
            exists: true
        });

        allBatchIds.push(batchId);

        emit BatchCreated(batchId, msg.sender, trustScore, ipfsCID);
    }

    /**
     * @dev Processor updates batch after processing & packaging.
     * @param batchId    The batch being processed
     * @param newCID     New IPFS CID with updated processing details
     */
    function processBatch(
        string memory batchId,
        string memory newCID
    ) public batchMustExist(batchId) {
        batches[batchId].ipfsCID = newCID;
        batches[batchId].status = BatchStatus.Processing;

        _addCustodyLog(batchId, msg.sender, msg.sender, "Processor");

        emit BatchStatusUpdated(batchId, BatchStatus.Processing);
    }

    /**
     * @dev Approve batch (no adulteration detected).
     */
    function approveBatch(string memory batchId) public batchMustExist(batchId) {
        batches[batchId].status = BatchStatus.Approved;
        emit BatchStatusUpdated(batchId, BatchStatus.Approved);
    }

    /**
     * @dev Flag batch for possible adulteration.
     * @param reason Short reason string
     */
    function flagBatch(
        string memory batchId,
        string memory reason
    ) public batchMustExist(batchId) {
        batches[batchId].status = BatchStatus.FlaggedAdulteration;
        flagged[batchId] = true;
        emit BatchFlagged(batchId, reason);
    }

    /**
     * @dev Distributor logs transport. Called when honey is in transit.
     * @param batchId     Batch being transported
     * @param locationCID IPFS CID with GPS/transport logs
     */
    function logTransport(
        string memory batchId,
        string memory locationCID
    ) public batchMustExist(batchId) {
        batches[batchId].status = BatchStatus.InTransit;

        custodyChain[batchId].push(TransferLog({
            from: msg.sender,
            to: msg.sender,
            role: "Distributor",
            timestamp: block.timestamp,
            locationCID: locationCID
        }));

        emit BatchStatusUpdated(batchId, BatchStatus.InTransit);
    }

    /**
     * @dev Mark batch as delivered to retailer.
     */
    function markDelivered(string memory batchId) public batchMustExist(batchId) {
        batches[batchId].status = BatchStatus.Delivered;
        emit BatchStatusUpdated(batchId, BatchStatus.Delivered);
    }

    // ─── Read Functions ──────────────────────────────────────────────────────

    /**
     * @dev Get full batch details. Called by consumer QR scan.
     */
    function getBatch(string memory batchId)
        public
        view
        batchMustExist(batchId)
        returns (
            string memory,
            address,
            uint256,
            string memory,
            BatchStatus,
            uint256
        )
    {
        HoneyBatch memory b = batches[batchId];
        return (b.batchId, b.beekeeper, b.trustScore, b.ipfsCID, b.status, b.createdAt);
    }

    /**
     * @dev Get full chain-of-custody logs for a batch.
     */
    function getCustodyChain(string memory batchId)
        public
        view
        batchMustExist(batchId)
        returns (TransferLog[] memory)
    {
        return custodyChain[batchId];
    }

    /**
     * @dev Get total number of batches.
     */
    function getTotalBatches() public view returns (uint256) {
        return allBatchIds.length;
    }

    // ─── Internal Helpers ────────────────────────────────────────────────────

    function _addCustodyLog(
        string memory batchId,
        address from,
        address to,
        string memory role
    ) internal {
        custodyChain[batchId].push(TransferLog({
            from: from,
            to: to,
            role: role,
            timestamp: block.timestamp,
            locationCID: ""
        }));
        emit CustodyTransferred(batchId, from, to, role);
    }
}